#!/bin/bash
set -iex 

# read plantuml syntax from stdin
while read x ; do PUML=${PUML}$'\n'$x ; done
PUML=${PUML}$'\n'"@enduml"

# encode plantuml syntax into image URL
IMGURL=$(curl ${PLANTUML_SERVER}/plantuml/form -d text="${PUML}" -v 2>&1 | grep Location | awk '{print $NF}' | sed 's/\/uml\//\/eps\//') 

# remove trailing linefeed
IMGURL=${PLANTUML_SERVER}${IMGURL%$'\r'} 

# get UML image from server
curl ${IMGURL}

