#!/bin/bash
set -iex 

# read plantuml syntax from stdin
while read x ; do PUML=${PUML}$'\n'$x ; done

# encode plantuml syntax into image URL
SVGURL=$(curl ${PLANTUML_SERVER}/plantuml/form -d text="${PUML}" -v 2>&1 | grep Location | awk '{print $NF}' | sed 's/\/uml\//\/svg\//') 

# remove trailing linefeed
SVGURL=${PLANTUML_SERVER}${SVGURL%$'\r'} 

# get UML image from server
curl ${SVGURL}

